# set this to the location where Kochiku web is running
kochiku_web_host: "104.236.206.38"
kochiku_web_protocol: "http"

# Change this if you want to run Redis on a different machine than the build master
# This needs to be the same as the Redis instance that the Kochiku application uses
redis_host: "104.236.206.38"

# Change this to the hostnames for the kochiku worker boxes that you want to deploy to
worker_hosts:
  - 104.236.201.83
